server:
  port: 8082
  servlet:
    context-path: /interest/auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: interest-auth
  datasource:
#    url: jdbc:mysql://123.206.215.203:3306/interest_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
#    username: interest_user
#    password: interest_user@123
    url: jdbc:mysql://127.0.0.1:3306/interest_user?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: wanghuan
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
logging:
# 你需要存储日志的目录
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest.auth: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.auth.model
#自定义配置
interest:
  paths-properties:
    image: D:/interest/file/image
#    image: 你需要存储图片的目录，如上
    domain-name: http://127.0.0.1:8080
#   domain-name: https://www.lovemtt.com
#   domain-name: 你的域名或者（ip+端口），如上
#  github:
#    client-id: 你在github中注册的client id
#    client-secret: 你在github中注册的client secret
#  qq:
#    appid: 你在qq中注册的appid
#    appkey: 你在qq中注册的appkey
  github:
    client-id: 89e5885a3b1e527ef739
    client-secret: 93a670a75ec971cc0b1f0339ac5a8a1ef6a405a0
  qq:
    appid: 101558281
    appkey: 4221f97d433b8f9209431f03fea12b26