server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: interest-zuul
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  sensitive-headers:
  routes:
    auth:
      path: /interest/auth/**
      serviceId: interest-auth
      stripPrefix: false
    user:
      path: /interest/user/**
      serviceId: interest-user
      stripPrefix: false
security:
  oauth2:
    client:
      access-token-uri: http://interest-auth/interest/auth/oauth/token
      user-authorization-uri: http://interest-auth/interest/auth/oauth/authorize
logging:
# 你需要存储日志的目录
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.cloud: DEBUG
    com.interest.zuul: DEBUG